<?xml version="1.0" encoding="ASCII"?>
<xmi:XMI xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore">
  <ecore:EPackage name="Grafcet" nsURI="http://Grafcet.fr" nsPrefix="Grafcet">
    <eClassifiers xsi:type="ecore:EClass" name="LocatedElement" abstract="true">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="location" ordered="false"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="NamedElement" abstract="true" eSuperTypes="#/0/LocatedElement">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" ordered="false"
          lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Grafcet" eSuperTypes="#/0/NamedElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="elements" ordered="false"
          upperBound="-1" eType="#/0/Element" containment="true" eOpposite="#/0/Element/grafcet"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="connections" ordered="false"
          upperBound="-1" eType="#/0/Transition"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Element" abstract="true" eSuperTypes="#/0/NamedElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="grafcet" ordered="false"
          lowerBound="1" eType="#/0/Grafcet" eOpposite="#/0/Grafcet/elements"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Step" eSuperTypes="#/0/Element">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="isInitial" ordered="false"
          lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="isActive" ordered="false"
          lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="action" ordered="false"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="incomingConnections"
          ordered="false" upperBound="-1" eType="#/0/Step"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="outgoingConnections"
          ordered="false" upperBound="-1" eType="#/0/Step"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Transition" eSuperTypes="#/0/Element">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="condition" ordered="false"
          lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="incomingConnections"
          ordered="false" lowerBound="1" eType="#/0/Step"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="outgoingConnections"
          ordered="false" lowerBound="1" eType="#/0/Step"/>
    </eClassifiers>
  </ecore:EPackage>
  <ecore:EPackage name="PrimitiveTypes" nsURI="PrimitiveTypes" nsPrefix="PrimitiveTypes"/>
</xmi:XMI>
